Add API objects files according to new structure suggested
oscar-mullin/api_PoC pull request #7
Opened 2017-02-20 15:19 UTC by WalterRamirezTX

2017-02-21 00:01 UTC, oscar-mullin requested changes

2017-02-21 00:01 UTC, oscar-mullin commented on test_specs/features/step_definitions/API_steps.rb
> +  unless response.code == 201
This should not be here. There should be a then in the steps that assert for the required error code and stuff.

2017-02-21 00:01 UTC, oscar-mullin commented on test_specs/features/step_definitions/API_steps.rb
> +# Get response for the Rest API Call and print it raw
We have to understand if we want to pass everything raw to idea or, if we want to get the other values in advance or hardcode them. It is not the responsibility of this test call the other APIs

2017-02-21 00:01 UTC, oscar-mullin commented on test_specs/features/support/API_Objects/category_api.rb
> +    communityAPI = CommunityAPI.new(false,nil)
Maybe we should provide default values to the initializer to avoid passing false and nil

2017-02-21 00:01 UTC, oscar-mullin commented on test_specs/features/APITest.feature
> +    Given I get the categories of "<site>" community with "<params>" parameters
We must assert something here in a then

2017-02-21 22:42 UTC, WalterRamirezTX commented on test_specs/features/step_definitions/API_steps.rb
> +# Get response for the Rest API Call and print it raw
Fixed on https://github.com/oscar-mullin/api_PoC/pull/7/commits/a502fe7f545bdbb79b3e17e8d1ca8b46851e5e6b Commit

2017-02-21 22:42 UTC, WalterRamirezTX commented on test_specs/features/step_definitions/API_steps.rb
> +  unless response.code == 201
Fixed on https://github.com/oscar-mullin/api_PoC/pull/7/commits/a502fe7f545bdbb79b3e17e8d1ca8b46851e5e6b Commit

2017-02-21 22:42 UTC, WalterRamirezTX commented on test_specs/features/support/API_Objects/category_api.rb
> +    communityAPI = CommunityAPI.new(false,nil)
Fixed on https://github.com/oscar-mullin/api_PoC/pull/7/commits/a502fe7f545bdbb79b3e17e8d1ca8b46851e5e6b Commit

2017-02-21 22:42 UTC, WalterRamirezTX commented on test_specs/features/APITest.feature
> +    Given I get the categories of "<site>" community with "<params>" parameters
Fixed on https://github.com/oscar-mullin/api_PoC/pull/7/commits/a502fe7f545bdbb79b3e17e8d1ca8b46851e5e6b Commit

2017-02-22 00:58 UTC, oscar-mullin approved these changes

2017-02-22 00:59 UTC, merged